# Generated by Django 4.2.4 on 2023-08-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('noise', models.IntegerField(blank=True, default=0, verbose_name='소음')),
                ('cleanness', models.IntegerField(blank=True, default=0, verbose_name='청결도')),
                ('accessibility', models.IntegerField(blank=True, default=0, verbose_name='접근성')),
                ('facility', models.IntegerField(blank=True, default=0, verbose_name='시설 및 장비')),
                ('average', models.FloatField(blank=True, default=0.0, verbose_name='평균')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
